#!/bin/bash
echo "Building jo.js"

cd js/core
cat _jo.js dom.js event.js subject.js time.js defer.js cache.js queue.js timer.js app.js > ../jo.js

cd ../data
cat data.js datasource.js record.js filesource.js script.js dispatch.js template.js post.js >> ../jo.js

cd ../ui
cat interface.js view.js container.js control.js button.js list.js busy.js caption.js card.js scroller.js stack.js divider.js expando.js expandotitle.js flexrow.js focus.js footer.js gesture.js group.js html.js input.js datetime.js label.js menu.js option.js passwordinput.js popup.js screen.js shim.js sound.js tabbar.js table.js textarea.js title.js toolbar.js form.js dialog.js selectlist.js navbar.js select.js toggle.js slider.js image.js canvas.js checkbox.js section.js homebutton.js link.js tab.js notification.js >> ../jo.js

cd ..
echo "Done."

echo "Minifying jo.js -> jo_min.js"
jsmin < jo.js > jo_min.js
# echo "Compiling jo.js -> jo_com.js"
# java -jar ~/bin/compiler.jar --js=jo.js --js_output_file=jo_com.js
# gzip -c jo_com.js > jo_com.js.gz
cd ..
echo "Done."


