UI = gesture.js \
	view.js \
	container.js \
	card.js \
	group.js \
	footer.js \
	stack.js \
	scroller.js \
	expando.js \
	control.js \
	button.js \
	input.js \
	textarea.js \
	focus.js \
	list.js \
	tabbar.js \
	title.js \
	caption.js \
	html.js \
	menu.js \
	sound.js \
	passwordinput.js \
	divider.js \
	label.js \
	table.js \
	flexrow.js \
	busy.js \
	stackscroller.js \
	toolbar.js \
	screen.js

ui:
	cat $(UI) >> ../jo.js
