UI = gesture.js \
	view.js \
	container.js \
	stack.js \
	scroller.js \
	control.js \
	button.js \
	input.js \
	focus.js \
	list.js \
	tabbar.js \
	title.js \
	html.js \
	menu.js \
	sound.js

ui:
	cat $(UI) >> ../jo.js
