#!/usr/bin/perl

sort(@ARGV);
$file = `cat @ARGV`;
$title = "Jo JavaScript Application Framework for HTML5";

print <<ENDDOC
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>$title</title>
	<meta name="generator" content="joDoc">
	<link rel="stylesheet" type="text/css" href="docbody.css">
	<link rel="stylesheet" type="text/css" href="doc.css">
	<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width">
	<meta name="format-detection" content="false">
</head>
<body>
<cite>Jo<cite>JavaScript App Framework</cite></cite>

$file

<br>
<cite><cite>Jo</cite></cite>
</body>
</html>
ENDDOC
